var base =
        [
            {id: 1, name: "Bulbasaur", nameRus: "Бульбазавр", maxCp: 1071},
            {id: 2, name: "Ivysaur", nameRus: "Ивизавр", maxCp: 1632},
            {id: 3, name: "Venusaur", nameRus: "Венозавр", maxCp: 2580},
            {id: 4, name: "Charmander", nameRus: "Чармандер", maxCp: 955},
            {id: 5, name: "Charmeleon", nameRus: "Чармелеон", maxCp: 1557},
            {id: 6, name: "Charizard", nameRus: "Чаризард", maxCp: 2602},
            {id: 7, name: "Squirtle", nameRus: "Сквиртл", maxCp: 1008},
            {id: 8, name: "Wartortle", nameRus: "Вартортл", maxCp: 1582},
            {id: 9, name: "Blastoise", nameRus: "Бластойз", maxCp: 2542},
            {id: 10, name: "Caterpie", nameRus: "Катерпи", maxCp: 443},
            {id: 11, name: "Metapod", nameRus: "Метапод", maxCp: 447},
            {id: 12, name: "Butterfree", nameRus: "Батерфри", maxCp: 1454},
            {id: 13, name: "Weedle", nameRus: "Видл", maxCp: 449},
            {id: 14, name: "Kakuna", nameRus: "Какуна", maxCp: 485},
            {id: 15, name: "Beedrill", nameRus: "Бидрилл", maxCp: 1439},
            {id: 16, name: "Pidgey", nameRus: "Пиджи", maxCp: 679},
            {id: 17, name: "Pidgeotto", nameRus: "Пиджеотто", maxCp: 1223},
            {id: 18, name: "Pidgeot", nameRus: "Пиджеот", maxCp: 2091},
            {id: 19, name: "Rattata", nameRus: "Раттата", maxCp: 581},
            {id: 20, name: "Raticate", nameRus: "Рэтикейт", maxCp: 1444},
            {id: 21, name: "Spearow", nameRus: "Спироу", maxCp: 686},
            {id: 22, name: "Fearow", nameRus: "Фироу", maxCp: 1746},
            {id: 23, name: "Ekans", nameRus: "Эканс", maxCp: 824},
            {id: 24, name: "Arbok", nameRus: "Эрбок", maxCp: 1767},
            {id: 25, name: "Pikachu", nameRus: "Пикачу", maxCp: 887},
            {id: 26, name: "Raichu", nameRus: "Райчу", maxCp: 2028},
            {id: 27, name: "Sandshrew", nameRus: "Сэндшру", maxCp: 798},
            {id: 28, name: "Sandslash", nameRus: "Сэндслэш", maxCp: 1810},
            {id: 29, name: "Nidoran female", nameRus: "Нидоран ж.", maxCp: 876},
            {id: 30, name: "Nidorina", nameRus: "Нидорина", maxCp: 1404},
            {id: 31, name: "Nidoqueen", nameRus: "Нидоквин", maxCp: 2485},
            {id: 32, name: "Nidoran male", nameRus: "Нидоран м.", maxCp: 843},
            {id: 33, name: "Nidorino", nameRus: "Нидорино", maxCp: 1372},
            {id: 34, name: "Nidoking", nameRus: "Нидокинг", maxCp: 2475},
            {id: 35, name: "Clefairy", nameRus: "Клефейри", maxCp: 1200},
            {id: 36, name: "Clefable", nameRus: "Клефейбл", maxCp: 2397},
            {id: 37, name: "Vulpix", nameRus: "Вульпикс", maxCp: 831},
            {id: 38, name: "Ninetales", nameRus: "Найнтейлс", maxCp: 2188},
            {id: 39, name: "Jigglypuff", nameRus: "Джиглипуф", maxCp: 917},
            {id: 40, name: "Wigglytuff", nameRus: "Виглитаф", maxCp: 2177},
            {id: 41, name: "Zubat", nameRus: "Зубат", maxCp: 642},
            {id: 42, name: "Golbat", nameRus: "Голбат", maxCp: 1921},
            {id: 43, name: "Oddish", nameRus: "Оддиш", maxCp: 1148},
            {id: 44, name: "Gloom", nameRus: "Глум", maxCp: 1689},
            {id: 45, name: "Vileplume", nameRus: "Вайлплюм", maxCp: 2492},
            {id: 46, name: "Paras", nameRus: "Парас", maxCp: 916},
            {id: 47, name: "Parasect", nameRus: "Парасект", maxCp: 1747},
            {id: 48, name: "Venonat", nameRus: "Венонат", maxCp: 1029},
            {id: 49, name: "Venomoth", nameRus: "Веномот", maxCp: 1890},
            {id: 50, name: "Diglett", nameRus: "Диглетт", maxCp: 456},
            {id: 51, name: "Dugtrio", nameRus: "Дагтрио", maxCp: 1168},
            {id: 52, name: "Meowth", nameRus: "Мяут", maxCp: 756},
            {id: 53, name: "Persian", nameRus: "Персиан", maxCp: 1631},
            {id: 54, name: "Psyduck", nameRus: "Псидак", maxCp: 1109},
            {id: 55, name: "Golduck", nameRus: "Голдак", maxCp: 2386},
            {id: 56, name: "Mankey", nameRus: "Манки", maxCp: 878},
            {id: 57, name: "Primeape", nameRus: "Праймейп", maxCp: 1864},
            {id: 58, name: "Growlithe", nameRus: "Гроули", maxCp: 1335},
            {id: 59, name: "Arcanine", nameRus: "Арканайн", maxCp: 2983},
            {id: 60, name: "Poliwag", nameRus: "Поливаг", maxCp: 795},
            {id: 61, name: "Poliwhirl", nameRus: "Поливирл", maxCp: 1340},
            {id: 62, name: "Poliwrath", nameRus: "Поливрат", maxCp: 2505},
            {id: 63, name: "Abra", nameRus: "Абра", maxCp: 600},
            {id: 64, name: "Kadabra", nameRus: "Кадабра", maxCp: 1131},
            {id: 65, name: "Alakazam", nameRus: "Алаказам", maxCp: 1813},
            {id: 66, name: "Machop", nameRus: "Мачоп", maxCp: 1089},
            {id: 67, name: "Machoke", nameRus: "Мачоук", maxCp: 1760},
            {id: 68, name: "Machamp", nameRus: "Мачамп", maxCp: 2594},
            {id: 69, name: "Bellsprout", nameRus: "Белспроут", maxCp: 1117},
            {id: 70, name: "Weepinbell", nameRus: "Випинбелл", maxCp: 1723},
            {id: 71, name: "Victrebel", nameRus: "Виктрибелл", maxCp: 2530},
            {id: 72, name: "Tentacool", nameRus: "Тентакул", maxCp: 905},
            {id: 73, name: "Tentacruel", nameRus: "Тентакруэль", maxCp: 2220},
            {id: 74, name: "Geodude", nameRus: "Джеодуд", maxCp: 849},
            {id: 75, name: "Graveler", nameRus: "Гравелер", maxCp: 1433},
            {id: 76, name: "Golem", nameRus: "Голем", maxCp: 2303},
            {id: 77, name: "Ponyta", nameRus: "Понита", maxCp: 1516},
            {id: 78, name: "Rapidash", nameRus: "Рапидаш", maxCp: 2199},
            {id: 79, name: "Slowpoke", nameRus: "Слоупок", maxCp: 1218},
            {id: 80, name: "Slowbro", nameRus: "Слоубро", maxCp: 2597},
            {id: 81, name: "Magnemite", nameRus: "Магнемайт", maxCp: 890},
            {id: 82, name: "Magneton", nameRus: "Магнетон", maxCp: 1879},
            {id: 83, name: "Farfetch'd", nameRus: "Фарфетчд", maxCp: 1263},
            {id: 84, name: "Doduo", nameRus: "Додуо", maxCp: 855},
            {id: 85, name: "Dodrio", nameRus: "Додрио", maxCp: 1836},
            {id: 86, name: "Seel", nameRus: "Сил", maxCp: 1107},
            {id: 87, name: "Dewgong", nameRus: "Дьюгонг", maxCp: 2145},
            {id: 88, name: "Grimer", nameRus: "Граймер", maxCp: 1284},
            {id: 89, name: "Muk", nameRus: "Мак", maxCp: 2602},
            {id: 90, name: "Shelder", nameRus: "Шелдер", maxCp: 822},
            {id: 91, name: "Cloyster", nameRus: "Клойстер", maxCp: 2052},
            {id: 92, name: "Gastly", nameRus: "Гастли", maxCp: 804},
            {id: 93, name: "Haunter", nameRus: "Хонтер", maxCp: 1380},
            {id: 94, name: "Gengar", nameRus: "Генгар", maxCp: 2078},
            {id: 95, name: "Onyx", nameRus: "Оникс", maxCp: 857},
            {id: 96, name: "Drowzee", nameRus: "Дроузи", maxCp: 1075},
            {id: 97, name: "Hypno", nameRus: "Гипно", maxCp: 2184},
            {id: 98, name: "Krabby", nameRus: "Крабби", maxCp: 792},
            {id: 99, name: "Kingler", nameRus: "Кинглер", maxCp: 1823},
            {id: 100, name: "Voltorb", nameRus: "Волторб", maxCp: 839},
            {id: 101, name: "Electrode", nameRus: "Электрод", maxCp: 1646},
            {id: 102, name: "Exeggcute", nameRus: "Эгзегут", maxCp: 1099},
            {id: 103, name: "Exeggutor", nameRus: "Эгзегутор", maxCp: 2955},
            {id: 104, name: "Cubone", nameRus: "Кьюбон", maxCp: 1006},
            {id: 105, name: "Marowak", nameRus: "Маровак", maxCp: 1656},
            {id: 106, name: "Hitmonlee", nameRus: "Хитмонтли", maxCp: 1492},
            {id: 107, name: "Hitmonchan", nameRus: "Хитмончан", maxCp: 1516},
            {id: 108, name: "Lickitung", nameRus: "Ликитунг", maxCp: 1626},
            {id: 109, name: "Koffing", nameRus: "Коффинг", maxCp: 1151},
            {id: 110, name: "Weezing", nameRus: "Визинг", maxCp: 2250},
            {id: 111, name: "Rhyhorn", nameRus: "Райхорн", maxCp: 1182},
            {id: 112, name: "Rhydon", nameRus: "Райдон", maxCp: 2243},
            {id: 113, name: "Chansey", nameRus: "Ченси", maxCp: 675},
            {id: 114, name: "Tangela", nameRus: "Танджела", maxCp: 1739},
            {id: 115, name: "Kangaskhan", nameRus: "Кангасхан", maxCp: 2043},
            {id: 116, name: "Horsea", nameRus: "Хорси", maxCp: 764},
            {id: 117, name: "Seadra", nameRus: "Сидра", maxCp: 1713},
            {id: 118, name: "Goldeen", nameRus: "Голдин", maxCp: 955},
            {id: 119, name: "Seaking", nameRus: "Сикинг", maxCp: 2043},
            {id: 120, name: "Staryu", nameRus: "Старью", maxCp: 937},
            {id: 121, name: "Starmie", nameRus: "Старми", maxCp: 2182},
            {id: 122, name: "Mr. Mime", nameRus: "Мистер Майм", maxCp: 1494},
            {id: 123, name: "Scyther", nameRus: "Скайтер", maxCp: 2073},
            {id: 124, name: "Jynx", nameRus: "Джинкс", maxCp: 1716},
            {id: 125, name: "Electabuzz", nameRus: "Электабазз", maxCp: 2119},
            {id: 126, name: "Magmar", nameRus: "Магмар", maxCp: 2265},
            {id: 127, name: "Pinsir", nameRus: "Пинсир", maxCp: 2121},
            {id: 128, name: "Tauros", nameRus: "Торос", maxCp: 1844},
            {id: 129, name: "Magicarp", nameRus: "Мэджикарп", maxCp: 262},
            {id: 130, name: "Gyarados", nameRus: "Гярадос", maxCp: 2688},
            {id: 131, name: "Lapras", nameRus: "Лапрас", maxCp: 2980},
            {id: 132, name: "Ditto", nameRus: "Дитто", maxCp: 919},
            {id: 133, name: "Eevee", nameRus: "Иви", maxCp: 1077},
            {id: 134, name: "Vaporeon", nameRus: "Вапореон", maxCp: 2816},
            {id: 135, name: "Jolteon", nameRus: "Джолтеон", maxCp: 2140},
            {id: 136, name: "Flareon", nameRus: "Флареон", maxCp: 2643},
            {id: 137, name: "Porygon", nameRus: "Поригон", maxCp: 1691},
            {id: 138, name: "Omanyte", nameRus: "Оманайт", maxCp: 1119},
            {id: 139, name: "Omastar", nameRus: "Омастар", maxCp: 2233},
            {id: 140, name: "Kabuto", nameRus: "Кабуто", maxCp: 1104},
            {id: 141, name: "Kabutops", nameRus: "Кабутопс", maxCp: 2130},
            {id: 142, name: "Aerodactyl", nameRus: "Аэродактиль", maxCp: 2165},
            {id: 143, name: "Snorlax", nameRus: "Снорлакс", maxCp: 3112},
            {id: 144, name: "Articuno", nameRus: "Артикуно", maxCp: 2978},
            {id: 145, name: "Zapdos", nameRus: "Запдос", maxCp: 3114},
            {id: 146, name: "Moltres", nameRus: "Молтрес", maxCp: 3240},
            {id: 147, name: "Dratini", nameRus: "Дратини", maxCp: 983},
            {id: 148, name: "Dragonair", nameRus: "Драгонэйр", maxCp: 1485},
            {id: 149, name: "Dragonite", nameRus: "Драгонайт", maxCp: 3500},
            {id: 150, name: "Mew", nameRus: "Мью", maxCp: 3299},
            {id: 151, name: "Mewtwo", nameRus: "Мьюту", maxCp: 4144}
        ];
var attackDexStandart =
        [
            {id: 1, name: "Acid", type: 3, damage: 10, energy: 7, timeout: 1.05, pokemonsHave: []},
            {id: 2, name: "Bite", type: 16, damage: 6, energy: 7, timeout: 0.5, pokemonsHave: []},
            {id: 3, name: "Bubble", type: 10, damage: 25, energy: 15, timeout: 2.3, pokemonsHave: []},
            {id: 4, name: "Bug Bite", type: 6, damage: 5, energy: 7, timeout: 0.45, pokemonsHave: []},
            {id: 5, name: "Bullet Punch", type: 8, damage: 10, energy: 7, timeout: 1.2, pokemonsHave: []},
            {id: 6, name: "Confusion", type: 13, damage: 15, energy: 7, timeout: 1.51, pokemonsHave: []},
            {id: 7, name: "Cut", type: 1, damage: 12, energy: 7, timeout: 1.13, pokemonsHave: []},
            {id: 8, name: "Dragon Breath", type: 15, damage: 6, energy: 7, timeout: 0.5, pokemonsHave: []},
            {id: 9, name: "Ember", type: 9, damage: 10, energy: 7, timeout: 1.05, pokemonsHave: []},
            {id: 10, name: "Feint Attack", type: 16, damage: 12, energy: 7, timeout: 1.04, pokemonsHave: []},
            {id: 11, name: "Fire Fang", type: 9, damage: 10, energy: 4, timeout: 0.84, pokemonsHave: []},
            {id: 12, name: "Frost Breath", type: 14, damage: 9, energy: 7, timeout: 0.81, pokemonsHave: []},
            {id: 13, name: "Fury Cutter", type: 6, damage: 3, energy: 12, timeout: 0.4, pokemonsHave: []},
            {id: 14, name: "Ice Shard", type: 14, damage: 15, energy: 7, timeout: 1.4, pokemonsHave: []},
            {id: 15, name: "Karate Chop", type: 2, damage: 6, energy: 7, timeout: 0.8, pokemonsHave: []},
            {id: 16, name: "Lick", type: 7, damage: 5, energy: 7, timeout: 0.5, pokemonsHave: []},
            {id: 17, name: "Low Kick", type: 2, damage: 5, energy: 7, timeout: 0.5, pokemonsHave: []},
            {id: 18, name: "Metal Claw", type: 8, damage: 12, energy: 7, timeout: 0.63, pokemonsHave: []},
            {id: 19, name: "Mud Shot", type: 4, damage: 12, energy: 7, timeout: 0.55, pokemonsHave: []},
            {id: 20, name: "Mud Slap", type: 4, damage: 15, energy: 9, timeout: 1.35, pokemonsHave: []},
            {id: 21, name: "Peck", type: 18, damage: 10, energy: 10, timeout: 1.15, pokemonsHave: []},
            {id: 22, name: "Poison Jab", type: 3, damage: 15, energy: 7, timeout: 1.05, pokemonsHave: []},
            {id: 23, name: "Poison Sting", type: 3, damage: 6, energy: 4, timeout: 0.58, pokemonsHave: []},
            {id: 24, name: "Pound", type: 1, damage: 7, energy: 7, timeout: 0.54, pokemonsHave: []},
            {id: 25, name: "Psycho Cut", type: 13, damage: 8, energy: 7, timeout: 0.57, pokemonsHave: []},
            {id: 26, name: "Quick Attack", type: 1, damage: 10, energy: 7, timeout: 1.33, pokemonsHave: []},
            {id: 27, name: "Razor Leaf", type: 11, damage: 15, energy: 7, timeout: 1.45, pokemonsHave: []},
        ];
